# Generated by Django 4.2.13 on 2024-06-20 13:46

from django.db import migrations
from authentication.models import Role

def create_roles(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    #Role = apps.get_model("authentication", "Role")
    #print(Role)
    dev = Role(slug="developer", name="Developer")
    dev.save()
    player = Role(slug="player", name="Giocatore")
    player.save()
    print(dev)
    print(player)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),        
    ]

    operations = [
        migrations.RunPython(create_roles)
    ]
