# Generated by Django 4.2.13 on 2024-06-24 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_game_cover_alter_gameattachment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('pen', 'In corso'), ('com', 'Completato')], default='pen', max_length=3)),
                ('order_date', models.DateTimeField()),
                ('payment_method', models.TextField(choices=[('pay', 'Paypal'), ('car', 'Carta di credito'), ('sat', 'Satispay')], default='pay', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='GameInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_games_game', to='games.game')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_games_order', to='orders.order')),
            ],
            options={
                'db_table': 'order_games',
            },
        ),
    ]
