# Generated by Django 4.2.13 on 2024-06-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_cover_alter_gameattachment_image'),
        ('orders', '0002_alter_order_order_date_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameinorder',
            unique_together={('game', 'order')},
        ),
    ]
