# Generated by Django 4.2.13 on 2024-06-24 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_cover_alter_gameattachment_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_alter_gameinorder_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_bought_game', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_bought_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_games',
                'unique_together': {('game', 'user')},
            },
        ),
    ]
