# Generated by Django 4.2.13 on 2024-06-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(default=None, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='gameattachment',
            name='image',
            field=models.ImageField(default=None, upload_to='attachments/'),
        ),
    ]
