# Generated by Django 4.2.13 on 2024-06-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='cause',
            field=models.CharField(choices=[('sp', 'Spam'), ('ot', 'Altro'), ('bo', 'È un bot'), ('sc', 'È un truffatore'), ('ha', 'Molestie')], default='ot', max_length=2),
        ),
        migrations.AlterModelTable(
            name='userreport',
            table='user_reports',
        ),
    ]
