# Generated by Django 4.2.13 on 2024-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendlist', '0003_alter_userreport_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='cause',
            field=models.CharField(choices=[('ha', 'Molestie'), ('bo', 'È un bot'), ('ot', 'Altro'), ('sp', 'Spam'), ('sc', 'È un truffatore')], default='ot', max_length=2),
        ),
    ]
