# Generated by Django 4.2.13 on 2024-06-23 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_cover_alter_gameattachment_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendlist', '0004_alter_userreport_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='cause',
            field=models.CharField(choices=[('ha', 'Molestie'), ('sp', 'Spam'), ('bo', 'È un bot'), ('sc', 'È un truffatore'), ('ot', 'Altro')], default='ot', max_length=2),
        ),
        migrations.CreateModel(
            name='GameReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField()),
                ('cause', models.CharField(choices=[('ex', 'Contenuti sessuali espliciti'), ('ha', "Incitazione all'odio"), ('ra', 'Razzismo'), ('sc', 'È una truffa'), ('ot', 'Altro')], default='ot', max_length=2)),
                ('game_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_reported', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_report_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_reports',
            },
        ),
    ]
