# Generated by Django 4.2.13 on 2024-06-23 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendlist', '0005_alter_userreport_cause_gamereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_A', to=settings.AUTH_USER_MODEL)),
                ('userB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_user_B', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friendships',
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pen', 'In attesa'), ('acc', 'Accettata'), ('den', 'Rifiutata')], default='pen', max_length=3)),
                ('user_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_requested', to=settings.AUTH_USER_MODEL)),
                ('user_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friend_requests',
            },
        ),
    ]
